trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      python -m unittest discover tests
    displayName: 'Run Tests'

  - template: bicep-azure-deploy.yml
    parameters:
      subscriptionId: '7b6f1e38-4253-4bcd-a6b4-2f242d4f7d19'
      resourceGroupName: 'rg-audit-dev'
      bicepFilePath: 'main.bicep'
