# azure-pipeline.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TestPythonCode
  displayName: 'Test Python Code'
  jobs:
  - job: PythonTest
    displayName: 'Test Python Application'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: python-test-template.yml
      parameters:
        python_version: '3.8'
